---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/zwave2mqtt
    build_args:
    - VERSION=${DRONE_TAG:-master}
    tags: ${DRONE_TAG:-master}-amd64

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/zwave2mqtt
    build_args:
    - VERSION=${DRONE_TAG:-master}
    - UPSTREAM_TAG=arm64v8-latest
    tags: ${DRONE_TAG:-master}-arm64

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-versioned
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    target: lansible/zwave2mqtt:${DRONE_TAG:-master}
    template: lansible/zwave2mqtt:${DRONE_TAG:-master}-ARCH
    platforms:
    - linux/amd64
    - linux/arm64

- name: manifest-latest
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    target: lansible/zwave2mqtt:latest
    template: lansible/zwave2mqtt:${DRONE_TAG:-master}-ARCH
    platforms:
    - linux/amd64
    - linux/arm64
  when:
    event:
    - tag

depends_on:
- amd64
- arm64
