---
  version: "3"
  services:
    zwave2mqtt:
      container_name: zwave2mqtt
      image: lansible/zwave2mqtt
      volumes:
        - ./store:/usr/src/app/store
      devices:
        - /dev/ttyACM0:/dev/ttyACM0
      restart: always
      network_mode: host
